# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.rcc.v1 import rmf_pb2 as protos_dot_rcc_dot_v1_dot_rmf__pb2


class RmfRccBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authenticate = channel.unary_unary(
                '/rcc_protos.RmfRccBridge/Authenticate',
                request_serializer=protos_dot_rcc_dot_v1_dot_rmf__pb2.AuthReq.SerializeToString,
                response_deserializer=protos_dot_rcc_dot_v1_dot_rmf__pb2.AuthResponse.FromString,
                )
        self.HealthCheck = channel.stream_stream(
                '/rcc_protos.RmfRccBridge/HealthCheck',
                request_serializer=protos_dot_rcc_dot_v1_dot_rmf__pb2.HealthRequest.SerializeToString,
                response_deserializer=protos_dot_rcc_dot_v1_dot_rmf__pb2.HealthResponse.FromString,
                )
        self.ConfigData = channel.unary_unary(
                '/rcc_protos.RmfRccBridge/ConfigData',
                request_serializer=protos_dot_rcc_dot_v1_dot_rmf__pb2.ConfigRequest.SerializeToString,
                response_deserializer=protos_dot_rcc_dot_v1_dot_rmf__pb2.ConfigResponse.FromString,
                )


class RmfRccBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RmfRccBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=protos_dot_rcc_dot_v1_dot_rmf__pb2.AuthReq.FromString,
                    response_serializer=protos_dot_rcc_dot_v1_dot_rmf__pb2.AuthResponse.SerializeToString,
            ),
            'HealthCheck': grpc.stream_stream_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=protos_dot_rcc_dot_v1_dot_rmf__pb2.HealthRequest.FromString,
                    response_serializer=protos_dot_rcc_dot_v1_dot_rmf__pb2.HealthResponse.SerializeToString,
            ),
            'ConfigData': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigData,
                    request_deserializer=protos_dot_rcc_dot_v1_dot_rmf__pb2.ConfigRequest.FromString,
                    response_serializer=protos_dot_rcc_dot_v1_dot_rmf__pb2.ConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rcc_protos.RmfRccBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RmfRccBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcc_protos.RmfRccBridge/Authenticate',
            protos_dot_rcc_dot_v1_dot_rmf__pb2.AuthReq.SerializeToString,
            protos_dot_rcc_dot_v1_dot_rmf__pb2.AuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/rcc_protos.RmfRccBridge/HealthCheck',
            protos_dot_rcc_dot_v1_dot_rmf__pb2.HealthRequest.SerializeToString,
            protos_dot_rcc_dot_v1_dot_rmf__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcc_protos.RmfRccBridge/ConfigData',
            protos_dot_rcc_dot_v1_dot_rmf__pb2.ConfigRequest.SerializeToString,
            protos_dot_rcc_dot_v1_dot_rmf__pb2.ConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
